### ISSUE TITLE
circularArray is thread safe?

### ISSUE THREAD

**Issue by aadog** [cuzfrog/tgods#13]
circularArray is thread safe?

**Comment by cuzfrog** [comment]
sorry, all basic collections are not thread-safe by design. I would possibly consider provide thread-safe implementations in the future. BTW, thanks

**Comment by aadog** [comment]
Thank you for your answer。
Your project is great, it just doesn't have concurrent versions,

I implemented a different list if you need it here.
https://github.com/aadog/dict-go

**Comment by aadog** [comment]
不过似乎大家都是国人,如果有可能并发版本似乎有效，因为它改变自gods
